import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/layout/Header";
import { getCurrentSession } from "@/actions/auth";
import { SanityLive } from "@/sanity/lib/live";
import HeaderCategorySelector from "@/components/layout/HeaderCategorySelector";
import Cart from "@/components/cart/Cart";
import Script from "next/script";

const inter = Inter({
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const { user } = await getCurrentSession(); 
   
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased min-h-[125vh]`}
      >
        <Header
         user={user}
         categorySelector={<HeaderCategorySelector />}
        />
        <Script
          src='https://cloud.umami.is/script.js'
          data-website-id='ad0ad03a-2ab0-4127-8f5e-b50c507fb626'
          strategy='beforeInteractive'
        />
         
        {children}
        <Cart />
        <SanityLive />
      </body>
    </html>
  );
};

export default RootLayout;
